# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Strong CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: CI by multiply java versions

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          # https://github.com/actions/setup-java?tab=readme-ov-file#install-multiple-jdks
          #
          # do NOT move old version 8.0.345 before 8, because the old version satified version 8
          java-version: |
            8
            8.0.345
            11
            17
            20
            21
          distribution: zulu
          cache: maven

      - name: Run integration test
        run: scripts/integration_test

      - name: Remove self maven install files
        run: rm -rf $HOME/.m2/repository/com/alibaba/dns-cache-manipulator*

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
